### ISSUE TITLE
Error while parsing few domains from the FOND benchmark

### ISSUE THREAD

**Issue by nitinef** [ssardina-research/pypddl-translator#4]
The PyPDDL parser fails at these FOND domains (from the fond-sat repo):

- Earth Observation
[domain_earth_observation.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952961/domain_earth_observation.txt)

REMOVE METRIC STATEMENTS - the rest is fixed

- Faults
[domain_faults.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952964/domain_faults.txt)

replace `(and)` with `(and (true))` and add predicate `(true)`

- First Responders
[domain_first_responders.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952967/domain_first_responders.txt)

lots of :requirements not accounted before, now they are

still there are many non-detet effects of the form `(and)` , they should be replaced with `(and (true))`

- Spiky Tireworld
[domain_spiky_tireworld.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952971/domain_spiky_tireworld.txt)

one `(and)` to fix

- Tireworld
[domain_tireworld.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952978/domain_tireworld.txt)

one `(and)` to fix

- Tireworld Truck
[domain_tireworld_truck.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952981/domain_tireworld_truck.txt)

two `(and)` to fix

- Zenotravel
[domain_zenotravel.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952984/domain_zenotravel.txt)

This has a forall  that is not yet handled:

![image](https://user-images.githubusercontent.com/2368384/175439079-08a3d448-0b45-4095-bb00-bb07c5fc96ea.png)

**Comment by ssardina** [comment]
OK this seems to be due to metrics:

![image](https://user-images.githubusercontent.com/2368384/174937711-91d1d282-46c7-4a0b-ac76-3fbfd8916c5b.png)

**Comment by ssardina** [comment]
Another issue is the use of constants, that is much more basic and should be incorporated into the parser for sure:

![image](https://user-images.githubusercontent.com/2368384/175175892-3d3c6622-43bc-4c2a-ba5e-326b2c53876b.png)

**Comment by ssardina** [comment]
faults is now working but we need to fix this which is very bad:

![image](https://user-images.githubusercontent.com/2368384/175437477-5b47482d-e673-4c48-b2eb-f06b4d6cb9e9.png)


Add predicate `true` and use:

![image](https://user-images.githubusercontent.com/2368384/175437503-24a7f10e-0bf6-43a1-8317-a60d48fa7087.png)

**Comment by ssardina** [comment]
- Zenotravel
[domain_zenotravel.txt](https://github.com/ssardina-planning/pypddl-translator/files/8952984/domain_zenotravel.txt)

This has a forall  that is not yet handled:

![image](https://user-images.githubusercontent.com/2368384/175439079-08a3d448-0b45-4095-bb00-bb07c5fc96ea.png)
